**Consider the below code to answer further questions:**

**import numpy as np**

**list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]**

**array_list = np.array(object = list_)**

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.**

Yes, there is difference between the data type of variables list_ and array_list. The data type of list_ is "list", and The data type of array_list is "numpy.ndarray" i.e. n dimensional numpy array. The data type of the elements inside list_ is "str" i.e. string and the data type of the elements inside array_list is "<U1" i.e. unicode string of length 1 character.

In [51]:
import numpy as np

list_ = ['1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [52]:
print("Printing the list_: ",list_)
print("Printing the array_list: ",array_list)
print("The data type of list_ is: ",type(list_))
print("The data type of array_list is: ",type(array_list))
print("The data type of the elements inside list_ is: ",type(list_[0]))
print("The data type of the elements inside array_list is: ",array_list.dtype)

Printing the list_:  ['1', '2', '3', '4', '5']
Printing the array_list:  ['1' '2' '3' '4' '5']
The data type of list_ is:  <class 'list'>
The data type of array_list is:  <class 'numpy.ndarray'>
The data type of the elements inside list_ is:  <class 'str'>
The data type of the elements inside array_list is:  <U1


**Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.**

In [54]:
print("Printing the data type of each element of the variable list_")
for i in range(len(list_)):
    print("The data type of the element {} inside list_ is: {}".format(list_[i],type(list_[i])))
print('\n')
print("Printing the data type of each element of the variable array_list")
for i in range(len(array_list)):
    print("The data type of the element {} inside array_list is: {}".format(list_[i],type(array_list[i])))
print('\n')
print("The most appropriate data type according to numpy that can represent all the element inside array_list is: {}".format(array_list.dtype))
print('\n')

Printing the data type of each element of the variable list_
The data type of the element 1 inside list_ is: <class 'str'>
The data type of the element 2 inside list_ is: <class 'str'>
The data type of the element 3 inside list_ is: <class 'str'>
The data type of the element 4 inside list_ is: <class 'str'>
The data type of the element 5 inside list_ is: <class 'str'>


Printing the data type of each element of the variable array_list
The data type of the element 1 inside array_list is: <class 'numpy.str_'>
The data type of the element 2 inside array_list is: <class 'numpy.str_'>
The data type of the element 3 inside array_list is: <class 'numpy.str_'>
The data type of the element 4 inside array_list is: <class 'numpy.str_'>
The data type of the element 5 inside array_list is: <class 'numpy.str_'>


The most appropriate data type according to numpy that can represent all the element inside array_list is: <U1




**NOTE:**

**<class 'str'>**: represents string object in python.

**<class 'numpy.str_'>**: represents numpy-specific string object in python.

**<U1**: represents that the elements of the numpy array is of the type unicode string having maximum length of 1.

**Q3. Considering the following changes in the variable, array_list:**

**array_list = np.array(object = list_, dtype = int)**

**Will there be any difference in the data type of the elements present in both the variables, list_ andarra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.**

Yes, the data type of the elements present in boththe variables list_, and array_list will be different after executing the statement "array_list = np.array(object = list_, dtype = int)".

The data type of the elements inside list_ is "str"(same as old) i.e. string and the data type of the elements inside array_list is "numpy.int64" i.e. 64-bit integer object in NumPy.

In [55]:
array_list = np.array(object = list_, dtype = int)

In [56]:
print("Printing the list_: ",list_)
print("Printing the array_list: ",array_list)
print('\n')

print("Printing the data type of each element of the variable list_")
for i in range(len(list_)):
    print("The data type of the element {} inside list_ is: {}".format(list_[i],type(list_[i])))
print('\n')

print("Printing the data type of each element of the variable array_list")
for i in range(len(array_list)):
    print("The data type of the element {} inside array_list is: {}".format(list_[i],type(array_list[i])))
print('\n')

print("The most appropriate data type according to numpy that can represent all the element inside array_list is: {}".format(array_list.dtype))
print('\n')

Printing the list_:  ['1', '2', '3', '4', '5']
Printing the array_list:  [1 2 3 4 5]


Printing the data type of each element of the variable list_
The data type of the element 1 inside list_ is: <class 'str'>
The data type of the element 2 inside list_ is: <class 'str'>
The data type of the element 3 inside list_ is: <class 'str'>
The data type of the element 4 inside list_ is: <class 'str'>
The data type of the element 5 inside list_ is: <class 'str'>


Printing the data type of each element of the variable array_list
The data type of the element 1 inside array_list is: <class 'numpy.int64'>
The data type of the element 2 inside array_list is: <class 'numpy.int64'>
The data type of the element 3 inside array_list is: <class 'numpy.int64'>
The data type of the element 4 inside array_list is: <class 'numpy.int64'>
The data type of the element 5 inside array_list is: <class 'numpy.int64'>


The most appropriate data type according to numpy that can represent all the element inside array

**NOTE:**

**<class 'str'>**: represents string object in python.

**<class 'numpy.int64'>**: 64-bit integer object in NumPy.

**Consider the below code to answer further questions:**

**import numpy as np**

**num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]**

**m_array = np.array(object = num_list)**

**Q4. Write a code to find the following characteristics of variable, num_array:**

**(i) shape**

**(ii) size**

In [57]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

m_array = np.array(object = num_list)

In [58]:
m_array_shape=np.shape(m_array)
print("The size of the array {} is: {}".format(m_array,m_array_shape))

m_array_size=np.size(m_array)
print("The size of the array {} is: {}".format(m_array,m_array_size))

The size of the array [[1 2 3]
 [4 5 6]] is: (2, 3)
The size of the array [[1 2 3]
 [4 5 6]] is: 6


"np.shape()" is a method present in numpy library that returns the shape of the numpy array. shape represents the the number of rows and the number of columns in the array in the form "(no_of_rows, n0_of_cols)".  "np" is an alias used for numpy.

"np.size()" is a method present in numpy library that returns the size of the numpy array. size of an array represents the total number of eelements present in the array.  "np" is an alias used for numpy.

**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.**

**[Hint: The size of the array will be 9 and the shape will be (3,3).]**

In [59]:
zero_array=np.zeros((3,3))
print(zero_array)
print(type(zero_array))
print('\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>




"np.zeros()" is a method present in numpy library of python that generates an array containing all zeros as per the size passed to "np.zeros()". "np" is an alias used for numpy.

"3*3", represents a 2-dimensional array. so, we pass "(3,3)" as arguement to "np.zeros()".

**Q6. Create an identity matrix of shape (5,5) using numpy functions?**

**[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]**

In [60]:
import numpy as np
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


An identity matrix is a matrix containing 1 diagonally and other elements will be 0., Identity matrix is always a square matrix.

shape(5,5) represents a square matrix containing 5 rows and 5 columns.

"eye()" is a method present in numpy library of python that generates an identity matrix as per the size passed to "np.eye()". "np" is an alias used for numpy.